# Docker Compose配置文件
# 项目管理系统

# 项目名称（避免中文和特殊字符）
name: project-management

services:
  # 项目管理系统应用
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: project-management-app
    restart: unless-stopped
    ports:
      - "5001:5001"  # 后端API端口
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-change-in-production}
      - DATABASE_PATH=/app/data/project_management.db
    volumes:
      # 数据持久化 - 数据库文件
      - ./data:/app/data
      # 日志持久化
      - ./logs:/app/logs
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Nginx反向代理（可选，用于生产环境）
  nginx:
    image: nginx:alpine
    container_name: project-management-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/dist:/usr/share/nginx/html:ro
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - app
    networks:
      - app-network
    profiles:
      - production  # 只在production profile下启动

networks:
  app-network:
    driver: bridge

volumes:
  data:
    driver: local
  logs:
    driver: local
